---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: client
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: metrics
  selector:
    app: etcd


